/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IslAmbulanceWlList {
    }
}
declare global {
    interface HTMLIslAmbulanceWlListElement extends Components.IslAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLIslAmbulanceWlListElement: {
        prototype: HTMLIslAmbulanceWlListElement;
        new (): HTMLIslAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "isl-ambulance-wl-list": HTMLIslAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface IslAmbulanceWlList {
    }
    interface IntrinsicElements {
        "isl-ambulance-wl-list": IslAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "isl-ambulance-wl-list": LocalJSX.IslAmbulanceWlList & JSXBase.HTMLAttributes<HTMLIslAmbulanceWlListElement>;
        }
    }
}
